### ISSUE TITLE
Odd-length hex values (leading zeros dropped)

### ISSUE THREAD

**Issue by Bouke** [idlesign/srptools#1]
I ran into an issue when testing this package against [my implementation of SRP in Swift](https://github.com/Bouke/SRP). Eventually I found that this package uses `'%x' % val` inside `def hex_from(val):` to convert (big) integers to hexadecimal. This method doesn't include any leading zero to make the hex output even length. For now I've worked around this [[example](https://github.com/Bouke/SRP/blob/master/remote.py)], but wanted to raise some awareness about this, as having odd-length hex values confused me a little.

**Comment by idlesign** [comment]
Agree, it might be somewhat confusing, and should be improved.
I'll try to do it this week.

**Comment by idlesign** [comment]
Implemented. Thank you.
