### ISSUE TITLE
Implementation incompatibilities due to stripping leading zeros

### ISSUE THREAD

**Issue by Bouke** [idlesign/srptools#2]
In the codebase, any hash is interpreted as an integer. However this loses some information on those hashes, namely the byte-length. I've run into an issue where `H(A|M|K)` was different between implementations. This was caused when srptools used a different value for calculated M;

    I: bouke
    p: test
    group parameters: 1024-bit
    s: 99e50c9ad1bd2856
    v: 52e3ee0cde007d2e7cee87acca1c041999b528e56dec925112d30a63d8e814231c2cd3bac9ae40220c44d63029912f1f7dda878e938ab5bfe7b87b854bb8385020d765054d07424eb5749fcd90344dbc0372432f6db25ae12cca4584ea72270ca61d831540b10919a31fde1b7b9e1cc7110429d8bbde1a6fe005896697b91436
    b: 57e997761d2aeb4c8dbfed9fde120c0ec730af1237e296f58649a6b3193ff21b36f5cfaed3049ee0051e5378f666f13d0c7c91040940a77a3ff1a461666c41e9aca3bd4747d74036e34941578553eb56d369638f796707425d0294809e81363fac90af29c7fde1ae142f8c280e3c2e17f9c4d68f644de5406aac7d378b812a34
    B: 0b3cc73f40a5fbdee992995dc26bfc43558803689798731fd303cdf18fdecbb5544f5caf960910f1b9449c772032be382b22d8763104781793553977bfdbd7cd3b05af0bf00deee22d76b477275e3294713711e3fe97f34724f9580bf2c055e78ae138664dfecaa2fe353768e30c3cc395541a929dc2af6a66e118ca937cffe8
    a: 2b557313c052bb0e24a3c7462e8f436769a54e8d325da794004cefab83ac8b71
    A: e18b11cddbfa709020fa2c67344a20e6704dba3e5ca6c4ca864b94ff5442965c80dfa751a9404feb2234fcd02d7f179dca4e308d76af173ec4eacc13a8daf0237bf19d4ac0ae9a4db885fdb46d5107caea8f71a8db39eda96d594e216c632a0d9720d84e8abb82b3dfa67fad099e1c67b13081bb564b2369c6db5f10358680b2
    M: 001961fb3aa5c24c437df55a18a41cabce3d57b4
    K: 86a5aff58ae7eca772b05bbb629f5b1c51677b14

    H(A|M|K) (my implementation): f0a6d49e5037f34b770a8e2de9ec5e3c0880953b
    H(A|M|K) (srptools): 1d1d4f0dde57072b3d060cabb7256d085fe0b051

**Comment by idlesign** [comment]
Thank you for the report.
I'll try to make a review this week. 
I'll help if you also provide `a` and `b` so we could make a full cycle.

**Comment by Bouke** [comment]
Thanks, I've added those values.

**Comment by idlesign** [comment]
Now values should match.
